run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/alexisbeaulieu97/yard
