version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - importas
    - forbidigo
    - contextcheck
    - gomodguard
    - bodyclose
    - gocritic
    - goconst
    - gocyclo
    - gosec
    - makezero
    - revive
    - unconvert
    - wsl_v5
    # Enable later once wrapping is consistent:
    # - wrapcheck
    # Optional low-noise extra:
    # - ineffassign
  disable:
    - depguard # broken in v2.5.0; re-enable when fixed

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - goconst
          - gosec
          - gocritic
          - gocyclo
      - path: ^cmd/yard/
        linters:
          - forbidigo

  settings:
    gocyclo:
      min-complexity: 10
    importas:
      no-unaliased: true
      alias:
        - pkg: github.com/stretchr/testify/assert
          alias: assert
        - pkg: github.com/stretchr/testify/require
          alias: require
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    forbidigo:
      forbid:
        - pattern: "fmt.Print.*"
          msg: "Use the structured logger instead of fmt.Print"
        - pattern: "log.Print.*"
          msg: "Use the structured logger instead of log.Print"

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/alexisbeaulieu97/yard

output:
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true
